let mySprite: Sprite = null
let dechets = 0
effects.starField.startScreenEffect()
scene.setBackgroundColor(11)
tiles.setTilemap(tilemap`niveau1`)
let heros = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff7777ff........
    .......f57777775f.......
    .......f77737777f.......
    ......fd77777777df......
    ......fd77777777df......
    ......fddd7777dddf......
    ......fbdbfddfbdbf......
    ......f5d5f11f5d5f......
    .......fb111111bf.......
    ......fff5db1b5ffff.....
    ....fc1115bfbf5111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, 0)
heros.setStayInScreen(true)
heros.y = 100
controller.moveSprite(mySprite)
