dechets: List[number] = []
effects.star_field.start_screen_effect()
scene.set_background_color(11)
tiles.set_tilemap(tilemap("""
    niveau1
"""))
heros = sprites.create(img("""
        ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff7777ff........
            .......f57777775f.......
            .......f77737777f.......
            ......fd77777777df......
            ......fd77777777df......
            ......fddd7777dddf......
            ......fbdbfddfbdbf......
            ......f5d5f11f5d5f......
            .......fb111111bf.......
            ......fff5db1b5ffff.....
            ....fc1115bfbf5111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
    """),
    0)
heros.set_stay_in_screen(True)
heros.y = 100
controller.move_sprite(heros, 100, 100)
info.set_life(3)